INSERT INTO ancient_names_pool (name, category, description, etymology) VALUES
('Anonim Amfora', 'hero', 'Sözler taşıyan gizemli bir arkeolog', 'Amphoreus (taşıyıcı)'),
('Uykusuz Epigrafist', 'scholar', 'Gece gündüz yazıtları çözen bilge', 'Epigraphia'),
('Perikles''in Hayaleti', 'philosopher', 'Ürpertici ama ustaca bir harita çizer', 'Perikles (Athen''in lideri)'),
('Troia''nın Temeli', 'artifact', 'Kazışlarda her zaman en dipteki tabaka', 'Troia (efsanevi şehir)'),
('Homeros''un Sevgili Kitabı', 'artifact', 'Her kelimenin bir hikayesi var', 'Homeros (İlyada yazarı)'),
('Ariadne''nin İpliği', 'hero', 'Labirent stratejistleri için kılavuz', 'Ariadne (Minos''un kızı)'),
('Delfoi Şifreleri', 'scholar', 'Mistik ve kripto-yazılar konusunda uzman', 'Delfoi (Apollon tapınağı)'),
('Midas''ın Dokunuşu', 'hero', 'Altın buluntularla konuşur', 'Kral Midas'),
('Sosyal Sokrates', 'philosopher', 'Sorularıyla her konuyu aydınlatır', 'Sokrates'),
('Platonik Gerçek', 'philosopher', 'İdeaları tartışan idealist bir araştırmacı', 'Platon'),
('Aristoteles''in Öğrencisi', 'scholar', 'Sistematik ve mantıklı analiz yapan', 'Aristoteles'),
('Heraklit''in Ateşi', 'philosopher', 'Her şey değişir, ama bu platform değişmez', 'Heraklit'),
('Diogenes''in Feneri', 'philosopher', 'Sahici olmayan her şeyi sorgulayan sinik', 'Diogenes'),
('Dr. Toz Bulutu', 'hero', 'Kazı sahasının en toza batmış kişi', 'Kazı deneyimi'),
('Çizim Ustası', 'scholar', 'Bitmeyen stratigrafik çizimlerle savaşan', 'Teknik bilgisi'),
('Mermer Yutağı', 'artifact', 'Antik yapı taşlarının sırrını bilen', 'Mermer işçiliği'),
('Şemsiye Unutkan', 'hero', 'Güneşteki günlerin gerçek kahramanı', 'Ege bölgesi sıcağı'),
('Fotoğrafçı', 'scholar', 'Her eşya için bin fotoğraf çeken', 'Fotoğrafçılık teknikleri'),
('Smyrna''nın Rüyası', 'philosopher', 'İzmir''in az bilinen detaylarını araştıran', 'Smyrna (eski İzmir)'),
('Efes''in Kütüphanecisi', 'artifact', 'Celsus Kütüphanesi''nin hayranı', 'Kütüphane mimarisi'),
('Bergama''nın Pergameni', 'scholar', 'Antik yazıtları ve parşömen''i inceliyor', 'Pergamon'),
('Halikarnasos''un Mozolesi', 'artifact', 'Büyük mezarlıkların mimarisini bilen', 'Halikarnasos (Bodrum)'),
('Çeşme''nin Korsanı', 'hero', 'Deniz ticaret rotalarından konuşan', 'Antik göçler');
